services:
  db:
    image: postgres:15.3
    container_name: ink-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ink-db
    ports:
      - "5432:5432"
    volumes:
      - ./ink_data:/var/lib/postgresql/data
    networks:
      - ink_network

networks:
  ink_network:
    driver: bridge
